### ISSUE TITLE
Joystick support???

### ISSUE THREAD

**Issue by ISA1716** [meatbroc/geofs-autothrottle#2]
Doesn't work with my Logitech Extreme 3D Pro, however, it does work well with mouse or keyboard.

**Comment by meatbroc** [comment]
What doesn't work? I don't use joystick myself so I didn't initially add joystick support.

**Comment by ISA1716** [comment]
So, CaN yOu AdD jOyStIcK sUpPoRt!?

**Comment by meatbroc** [comment]
I'll do my best. It might take me a while to get around to it though.

**Comment by meatbroc** [comment]
Just to be clear, can you tell me what about this script doesn't work?

**Comment by ISA1716** [comment]
**Start of detailed explanation**

When you engage the A/THR, if you're using a flightstick, the A/T practically does nothing. The throttle is still controlled by your external throttle stick, not the autothrottle. So the way you could make it better is that    you could update the script so then it lets you engage and disengage the A/T using available programmable buttons on your flightstick and that when the A/THR is engaged it makes the game ignore any movement of the throttle, but still lets you control the yaw, pitch and roll with the flightstick and also lets you use the buttons.

**End of detailed explanation**

**Comment by ISA1716** [comment]
Also, on the detailed explanation, I also added some suggestions of other things you could add too.

**Comment by meatbroc** [comment]
Ah I see. I don't fully understand how GeoFS supports joysticks and external throttles, since I don't own either, but I'll try my best. Thanks for the explanation

**Comment by meatbroc** [comment]
Ok I've implemented tentative joystick support, go ahead and test it out and let me know how it goes.

**Comment by ISA1716** [comment]
Still doesn't work. by the way, when you try next, remember to add ALL of these : Make it so then it engages and disengage the A/T using available programmable buttons on your flightstick and that when the A/THR is engaged it makes the game ignore any movement of the throttle, but still lets you control the yaw, pitch and roll with the flightstick and also lets you use the buttons (so basically add more things that cou can program your programmable buttons to do).

**Comment by meatbroc** [comment]
Are you sure you added the new version? I tried to override regular throttle movement but I don't think there's a way to add support if I can't debug it.

**Comment by meatbroc** [comment]
Actually to help me debug, can you run this code in your console, move your throttle quadrants, and tell me what the output looks like?
```js
controls.updateJoystick = function(e) {
    if (controls.joystick.poll()) {
        for (var t in controls.joystick.axes) {
            let a = controls.joystick.axes[t]
              , o = geofs.preferences.joystick.axis[t]
              , n = geofs.preferences.joystick.calibration[t] || {
                center: 0,
                multiplier: 1
            };
            if ("none" != o) {
                var r = controls.axisSetters[o];
                if (r && (!geofs.autopilot.on || r.overridesAutopilot) && (!flight.sharing.on || multiplayer.flightSharing.control || !r.overridesPeer) && !flight.recorder.playing) {
                    var s = controls.joystick.getAxisValue(t, r.min, r.max);
                    if (controls.joystick.calibrating) {
                        a.range.max = Math.max(a.range.max, s),
                        a.range.min = Math.min(a.range.min, s);
                        let c = a.range.max - a.range.min, d;
                        n = {
                            center: a.range.min + c / 2,
                            multiplier: 2 / c
                        },
                        geofs.preferences.joystick.calibration[t] = n
                    }
                    s = (s - n.center) * n.multiplier,
                    geofs.preferences.joystick.multiplier[t] && (s *= -1),
                    r.process && r.process(s, e)
                    console.log("axis: " + o)
                    console.log("setter: " + r)
                }
            }
        }
        if (controls.joystick.buttons)
            for (var t in controls.joystick.buttons) {
                var u, p = controls.joystick.buttons[t];
                if (p && "none" != geofs.preferences.joystick.buttons[t]) {
                    var h = p.oldValue
                      , m = controls.joystick.checkButton(t);
                    if (m != h) {
                        try {
                            if (m)
                                var u = controls.joystick.buttonHandlers.buttondown[t];
                            else
                                var u = controls.joystick.buttonHandlers.buttonup[t]
                        } catch (f) {}
                        if (u)
                            for (var g = 0; g < u.length; g++)
                                u[g](e);
                        p.oldValue = m
                    }
                }
            }
    }
}
```

**Comment by ISA1716** [comment]
ok. havent tried it yet, my screen time is up for the day according to my
parents

**Comment by meatbroc** [comment]
Aight lmk when you do try it

**Comment by ISA1716** [comment]
Still doesn't work.

**Comment by meatbroc** [comment]
Ok, can you try to run the code I sent and move your throttle quadrants. This is so I can figure out how GeoFS handles joysticks.

**Comment by ISA1716** [comment]
still doesn't work.

**Comment by meatbroc** [comment]
Try the new version. According to a different tester it should work now.

**Comment by ISA1716** [comment]
same answer as before. doesn't work.

**Comment by meatbroc** [comment]
I don't know what to tell you. Unless you can work with me in debugging by running the code i sent previously, I don't know how I can get this to work for you.
